version: '3.8'

services:


  qdrant:
    image: qdrant/qdrant:latest
    container_name: docunexus_vector_db
    ports:
      - "6333:6333" 
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    networks:
      - docunexus_network


  redis:
    image: redis:alpine
    container_name: docunexus_broker
    ports:
      - "6379:6379"
    networks:
      - docunexus_network

networks:
  docunexus_network:
    driver: bridge